
-- 관리자(pw:1234)
INSERT INTO ADMIN_TB VALUES('admin1', '$2a$10$gze1/SwRC7AVCOMhJ6VC0ealimLNQfaQykGKbBi7vKERGHuD5zsye', '관리자', sysdate);

-- 회원
INSERT INTO MEMBERS_TB VALUES('hello', '$2a$10$gze1/SwRC7AVCOMhJ6VC0ealimLNQfaQykGKbBi7vKERGHuD5zsye', '김인사', '인사맨',
'010-1234-5678', 'helloman@naver.com', '12345', '서울특별시 용산구 인사동', '인사아파트 110동 101호', 0, SYSDATE, NULL, '123', 'Y'); 

-- 카테고리
INSERT INTO CATEGORY_TB VALUES ('1', NULL, '전체');
INSERT INTO CATEGORY_TB VALUES ('2', '1', '아우터');
INSERT INTO CATEGORY_TB VALUES ('3', '1', '티셔츠');
INSERT INTO CATEGORY_TB VALUES ('4', '1', '셔츠');
INSERT INTO CATEGORY_TB VALUES ('5', '1', '팬츠');
INSERT INTO CATEGORY_TB VALUES ('6', '1', '신발');
INSERT INTO CATEGORY_TB VALUES ('7', '2', '가디건');
INSERT INTO CATEGORY_TB VALUES ('8', '2', '자켓');
INSERT INTO CATEGORY_TB VALUES ('9', '2', '코트');
INSERT INTO CATEGORY_TB VALUES ('10', '3', '맨투맨');
INSERT INTO CATEGORY_TB VALUES ('11', '3', '후드');
INSERT INTO CATEGORY_TB VALUES ('12', '3', '니트');
INSERT INTO CATEGORY_TB VALUES ('13', '4', '베이직/데님');
INSERT INTO CATEGORY_TB VALUES ('14', '4', '스트라이프');
INSERT INTO CATEGORY_TB VALUES ('15', '4', '체크/패턴');
INSERT INTO CATEGORY_TB VALUES ('16', '5', '데님');
INSERT INTO CATEGORY_TB VALUES ('17', '5', '슬랙스');
INSERT INTO CATEGORY_TB VALUES ('18', '5', '면바지');
INSERT INTO CATEGORY_TB VALUES ('19', '6', '스니커즈');
INSERT INTO CATEGORY_TB VALUES ('20', '6', '로퍼');
INSERT INTO CATEGORY_TB VALUES ('21', '6', '샌들');